
package com.epam.mentoring.ws.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RandomNumberGeneratorImplService", targetNamespace = "http://endpoint.ws.mentoring.epam.com/", wsdlLocation = "http://localhost:8081/rand?wsdl")
public class RandomNumberGeneratorImplService
    extends Service
{

    private final static URL RANDOMNUMBERGENERATORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RANDOMNUMBERGENERATORIMPLSERVICE_EXCEPTION;
    private final static QName RANDOMNUMBERGENERATORIMPLSERVICE_QNAME = new QName("http://endpoint.ws.mentoring.epam.com/", "RandomNumberGeneratorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/rand?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RANDOMNUMBERGENERATORIMPLSERVICE_WSDL_LOCATION = url;
        RANDOMNUMBERGENERATORIMPLSERVICE_EXCEPTION = e;
    }

    public RandomNumberGeneratorImplService() {
        super(__getWsdlLocation(), RANDOMNUMBERGENERATORIMPLSERVICE_QNAME);
    }

    public RandomNumberGeneratorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RANDOMNUMBERGENERATORIMPLSERVICE_QNAME, features);
    }

    public RandomNumberGeneratorImplService(URL wsdlLocation) {
        super(wsdlLocation, RANDOMNUMBERGENERATORIMPLSERVICE_QNAME);
    }

    public RandomNumberGeneratorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RANDOMNUMBERGENERATORIMPLSERVICE_QNAME, features);
    }

    public RandomNumberGeneratorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RandomNumberGeneratorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RandomNumberGenerator
     */
    @WebEndpoint(name = "RandomNumberGeneratorImplPort")
    public RandomNumberGenerator getRandomNumberGeneratorImplPort() {
        return super.getPort(new QName("http://endpoint.ws.mentoring.epam.com/", "RandomNumberGeneratorImplPort"), RandomNumberGenerator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandomNumberGenerator
     */
    @WebEndpoint(name = "RandomNumberGeneratorImplPort")
    public RandomNumberGenerator getRandomNumberGeneratorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.ws.mentoring.epam.com/", "RandomNumberGeneratorImplPort"), RandomNumberGenerator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RANDOMNUMBERGENERATORIMPLSERVICE_EXCEPTION!= null) {
            throw RANDOMNUMBERGENERATORIMPLSERVICE_EXCEPTION;
        }
        return RANDOMNUMBERGENERATORIMPLSERVICE_WSDL_LOCATION;
    }

}
