
package com.epam.mentoring.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RandomNumberGenerator", targetNamespace = "http://endpoint.ws.mentoring.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RandomNumberGenerator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.ws.mentoring.epam.com/RandomNumberGenerator/generateRequest", output = "http://endpoint.ws.mentoring.epam.com/RandomNumberGenerator/generateResponse")
    public int generate(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

}
